apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: company-brain-ai-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
  - host: company-brain.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: company-brain-ai-service
            port:
              number: 80