apiVersion: apps/v1
kind: Deployment

metadata:
  name: company-brain-ai

spec:
  replicas: 2

  selector:
    matchLabels:
      app: company-brain-ai

  template:
    metadata:
      labels:
        app: company-brain-ai

    spec:
      containers:
        - name: company-brain-ai
          image: company-brain-ai:v5
          imagePullPolicy: IfNotPresent

          volumeMounts:
            - name: secret-volume
              mountPath: "/app/secrets"
              readOnly: true

          volumeMounts:
            - name: app-storage
              mountPath: /app/data

          ports:
          - containerPort: 8000

          env:
          - name: APP_VERSION
            valueFrom:
              configMapKeyRef:
                name: company-brain-config
                key: APP_VERSION

          - name: SERVICE_NAME
            valueFrom:
              configMapKeyRef:
                name: company-brain-config
                key: SERVICE_NAME

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: company-brain-secret
                key: DB_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: company-brain-secret
                key: DB_PASSWORD

      volumes:
        - name: secret-volume
          secret:
            secretName: company-brain-secret

      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: company-brain-pvc